### ISSUE TITLE
How to style with vuetify?

### ISSUE THREAD

**Issue by mhml1367** [alireza-ab/vue-persian-datepicker#10]
![image](https://user-images.githubusercontent.com/25319239/150738664-02f39505-fcb7-43d8-9cb3-f7a9d4037b87.png)
example :
in inpute: 1400/11/04

**Comment by mhml1367** [comment]
![image](https://user-images.githubusercontent.com/25319239/152627549-702d99e2-b1cf-45c4-82ea-9de4434954b2.png)

**Comment by alireza-ab** [comment]
Hi @mhml1367 
You can use this https://alireza-ab.ir/datepicker/color-and-styles#styles or add your specific styles in CSS files.

example:
```scss
.pdp-input {
   border: 1px solid red;
}
```
