### ISSUE TITLE
How to set default value to range Date picker?

### ISSUE THREAD

**Issue by hamed2867** [alireza-ab/vue-persian-datepicker#11]
I wanna set default value to range date picker as : `['2022-02-20 19:13', '2022-02-21 19:13']` in data section
But this Error Happen:
`Error in mounted hook: "TypeError: e.some is not a function"`

how can I solve it?

**Comment by alireza-ab** [comment]
Hi @hamed2867 

With this way: 
```vue
<date-picker v-model="date" type="datetime" />
```
```js
data() {
    return {
        date: ['2022-02-20 19:13', '2022-02-21 19:13']
    }
}
```

**Comment by hamed2867** [comment]
> 

thank you for your answer, I create Component from your datePicker and call as below:


```
              <my-ab-date-picker
                  :mode="'range'"
                  :type="'datetime'"
                  :locale="'fa,en'"
                  click-on="all"
                  clearable
                  :show="false"
                  :auto-submit="true"
                  :column="2"
                  v-model="searchDate"
                  :toIso="false"
              >
```


and in data:

```
data() {
    return {
               searchDate: ['2022-02-20 19:13', '2022-02-21 19:13'],
         }
}
```

but it doesn't work and **(Error in mounted hook: "TypeError: e.some is not a function")** showed
Do you have any idea for it?

**Comment by alireza-ab** [comment]
Could you also show me the `toUTC` function?

---
In addition, you can use `PersianDate` instead of `moment` to improve your code.
```js
import datePicker, {PersianDate} from '@alireza-ab/vue-persian-datepicker'
```
documentation: https://alireza-ab.ir/persian-date

**Comment by hamed2867** [comment]
> Could you also show me the `toUTC` function?
> 
> In addition, you can use `PersianDate` instead of `moment` to improve your code.
> 
> ```js
> import datePicker, {PersianDate} from '@alireza-ab/vue-persian-datepicker'
> ```
> 
> documentation: https://alireza-ab.ir/persian-date

```
        toUTC(value) {
            return moment.from(value).format("YYYY-MM-DD HH:mm")
        },
```

**Comment by alireza-ab** [comment]
change the function to this:
```js
toUTC(value){
   if(Array.isArray(value))
      return value.map(date => moment.from(date).format("YYYY-MM-DD HH:mm"))
   return moment.from(value).format("YYYY-MM-DD HH:mm")
}
```

**Comment by honarmanly** [comment]
I have the same requirement to set initial value while loading the page containing date-picker. but I need to set the value dynamically. in your example answer here you set the range statically. Is there any solution?

**Comment by alireza-ab** [comment]
Hi @honarmanly 
Please read this #4.

**Comment by hamed2867** [comment]
> change the function to this:
> 
> ```js
> toUTC(value){
>    if(Array.isArray(value))
>       return value.map(date => moment.from(date).format("YYYY-MM-DD HH:mm"))
>    return moment.from(value).format("YYYY-MM-DD HH:mm")
> }
> ```

Thank you for Your answer.

**Comment by hamed2867** [comment]
> I have the same requirement to set initial value while loading the page containing date-picker. but I need to set the value dynamically. in your example answer here you set the range statically. Is there any solution?

try this: 

```
data() {
    return {
               searchDate: this.getDefaultDateItems(),
         }
},
  methods: {
    getDefaultDateItems(){
      let startDate = new Date();
      startDate.setHours(0, 0, 0);
      let endDate = new Date();
      endDate.setHours(23, 59, 59);
      return [startDate,endDate];
    },
}
```
