### ISSUE TITLE
nuxt app crashes while in ssr mode and page scroll occurs

### ISSUE THREAD

**Issue by honarmanly** [alireza-ab/vue-persian-datepicker#14]
I have a nuxt application with PWA enabled. as I add date-picker to page while ssr is enabled and if page scrolls the page crashes

**Comment by alireza-ab** [comment]
What is the error?
Could you show your code?

**Comment by d4rkr3pt0r** [comment]
@honarmanly I've load it in my nuxt project with SSR and PWA enabled. Eveything works fine. You may load the module incorrectly.
Check this method:
```
<template>
	<client-only>
		<DatePicker></NewDatePicker>
	</client-only>
</template>
<script>
export default {
	components: {
		'DatePicker': () => import ('@alireza-ab/vue-persian-datepicker'),
	},
}
</script>
```
