### ISSUE TITLE
get display value

### ISSUE THREAD

**Issue by Mohammad99k** [alireza-ab/vue-persian-datepicker#16]
Hi
how can I get the display value?
```
var date = new Vue({
              ...
            });
```

**Comment by alireza-ab** [comment]
Hi @Mohammad99k 

If you mean that date user selected, with this way you can get it:
```html
<date-picker v-model="date"></date-picker>
```
```js
<script>
export default {
  data(){
    return {
      date:null
    }
  }
}
</script>
```

**Comment by Mohammad99k** [comment]
actually I have v-model and display format is different from output format. I want access date as display format of date than user select.

**Comment by alireza-ab** [comment]
Please see this https://alireza-ab.ir/datepicker/formatting#output-format.
