### ISSUE TITLE
clear button and set manually

### ISSUE THREAD

**Issue by Mohammad99k** [alireza-ab/vue-persian-datepicker#17]
Hi
I have two questions:
1. Which event call when click clear button?
2. How to set manually date or time? When I set value in input clear button not working so must be a way that set value and set input value to.

**Comment by alireza-ab** [comment]
Hi @Mohammad99k 
1. When the clear button is clicked, any event is not called. just model value is cleared.
2. Please see this #4.

**Comment by Mohammad99k** [comment]
thank you vert much
Is there a way that do some thing after clear btn clicked?
