### ISSUE TITLE
warning در ناکست

### ISSUE THREAD

**Issue by id1385** [alireza-ab/vue-persian-datepicker#18]
![image](https://user-images.githubusercontent.com/28746285/166638044-adf48813-26d2-4f5d-b169-23da6a494b4d.png)
سلام من نصب کردم روی ناکست 2 

موقع اجرا این خطا میاد ولی کار میکنه !

**Comment by d4rkr3pt0r** [comment]
@id1385 
https://github.com/alireza-ab/vue-persian-datepicker/issues/14#issuecomment-1065134313

**Comment by alireza-ab** [comment]
Hi @id1385
Now, this has been fixed.
