### ISSUE TITLE
package improvements

### ISSUE THREAD

**Issue by pi0** [alireza-ab/vue-persian-datepicker#2]
Nice work @alireza-ab <3

Some suggestions:
- Avoid depending on `node_modules` structure. Current module implementation, tries to add template from another package (../persian-date/lib/plugin.js). We may instead use `this.addModule('@alireza-ab/persian-date/lib/nuxt')` and add it as dependency
- Use `files` field in package.json to only include `src` and `nuxt.js` in final pkg (see [unpkg](https://unpkg.com/browse/@alireza-ab/vue-persian-datepicker@2.0.0/). currently everything is published)
- In nuxt documentation, mention `components` option should be `true` in nuxt.config

**Comment by alireza-ab** [comment]
Thank you @pi0.

I'm adding these suggestions soon. 🙂
