### ISSUE TITLE
Bug with the new version

### ISSUE THREAD

**Issue by farshidbeheshti** [alireza-ab/vue-persian-datepicker#20]
The arrow keys, to swicth between dates, are disable **when the datepicker opens on the current date** (See the attachment)
![image](https://user-images.githubusercontent.com/1665275/174560325-ad7a596b-7c9e-47b4-a253-1d057c22391c.png)

There is **NO** such issue when the datepicker is on Gregorian calendar or if open the datepicker on a date different than current month.

Farshid

**Comment by alireza-ab** [comment]
Hi guys! @farshidbeheshti @AmirmohammadBeheshti 
I apologize for being late in answering.
This problem has now been fixed.
Thanks for your patience and for reporting the bug. :pray:
