### ISSUE TITLE
مشکل کار با localconfig

### ISSUE THREAD

**Issue by mrmfamin** [alireza-ab/vue-persian-datepicker#21]
سلام

این کدمه:
`<date-picker from="" mode="range" locale="fa,en" locale-config="{fa: {'displayFormat': 'jYYYY/jMM/jDD','inputFormat': 'jYYYY/jMM/jDD'},en: {'displayFormat': 'YYYY/MM/DD','inputFormat': 'YYYY/MM/DD'}}"></date-picker>`

این ارور رو میده:
`[Vue warn]: Invalid prop: type check failed for prop "localeConfig". Expected Object, got String with value "{fa: {'displayFormat': 'jYYYY/jMM/jDD','inputFormat': 'jYYYY/jMM/jDD'},en: {'displayFormat': 'YYYY/MM/DD','inputFormat': 'YYYY/MM/DD'}}".`

**Comment by alireza-ab** [comment]
Hi @mrmfamin 

Write like this
```vue
<data-picker :locale-config="{fa: {'displayFormat': 'jYYYY/jMM/jDD','inputFormat': 'jYYYY/jMM/jDD'},en: {'displayFormat': 'YYYY/MM/DD','inputFormat': 'YYYY/MM/DD'}}" />
```
