### ISSUE TITLE
custom attributes

### ISSUE THREAD

**Issue by mrmfamin** [alireza-ab/vue-persian-datepicker#22]
Hi
Is there any way to add some **attributes** to input which made by datepicker?

**Comment by mrmfamin** [comment]
سلام
راهی برای اضافه کردن attributes به اینپوتی که توسط datepicker ساخته میشه وجود داره؟

**Comment by alireza-ab** [comment]
Hi @mrmfamin 
Please read this: https://alireza-ab.ir/datepicker/attributes#

**Comment by mrmfamin** [comment]
Thanks
But I need **custom** attributes like **data-x** to add on input!
How can i do this?

**Comment by alireza-ab** [comment]
Just add it.
```vue
<date-picker data-x="test" />
// or
<date-picker input-data-x="test" />
```
