### ISSUE TITLE
ست كردن تاريخ جهت نمايش

### ISSUE THREAD

**Issue by bensaeed** [alireza-ab/vue-persian-datepicker#28]
سلام
ست كردن تاريخ بر اساس ديتاي خوانده شده از ديتابيس در صفحه وب به چه صورت مي باشد ؟
امكانش هست راهنمايي بفرمائيد.
زبان برنامه نويسی :
Asp.net MVC
C#

قطعه كدي كه نياز دارم تاريخ در آن نمايش داده شود :
<div id="Date" name="Date">
         <date-picker :column="1" mode="single" id="VoucherDate" name="VoucherDate"> مكان نمايش دادن تاريخ</date-picker>
</div>

با تشكر

**Comment by alireza-ab** [comment]
سلام @bensaeed 
این مورد رو مطالعه کنید: #4
