### ISSUE TITLE
نمایش تاریخ شمسی به جای تاریخ میلادی

### ISSUE THREAD

**Issue by sbajam** [alireza-ab/vue-persian-datepicker#29]
سلام  با اینکه تقویم شمسی نشان داده می‌شود ولی 
وقتی تاریخ انتخاب می‌شود تاریخ میلادی آن نشان داده می‌شود
درصورتی که من به تاریح شمسی نیازمندم

```
 <date-picker :column="1" mode="single" v-model="date" locale="fa" :modal="true"
                                input-format="YYYY-MM-DD" />
```

**Comment by alireza-ab** [comment]
سلام @sbajam 
این صفحه رو مطالعه کنید: https://alireza-ab.ir/datepicker/formatting
input-format: قالب نمایش تاریخ داخل اینپوت رو مشخص میکنه
format: قالب تاریخ v-model رو مشخص میکنه
display-format: قالب نمایش تاریخ داخل فوتر تقویم رو مشخص میکنه
