### ISSUE TITLE
ایجاد فیلد الزامی

### ISSUE THREAD

**Issue by Mohammad99k** [alireza-ab/vue-persian-datepicker#32]
با سلام و وقت بخیر
چطور میشه Required رو به input اضافه کرد؟
در واقع در فرم فیلد تاریخ الزامی باشد؟

**Comment by Mohammad99k** [comment]
با سلام مجدد 
این مشکل برطرف شد
فقط متوجه یک باگ شدم
هنگامی که alternative-field تظیم کردیم و :auto-submit="false" است، با تغییر تاریخ بدون انتخاب (زدن دکمه تایید) مقدار alternative-field تغییر میکند با اینکه تایید زده نشده است

**Comment by alireza-ab** [comment]
سلام وقتتون بخیر
ببخشید که اینقدر دیر جواب میدم
بله درسته این باگ وجود داره و من سعی میکنم در اولین فرصت این مشکل رو حل کنم.
ممنون از شما

**Comment by jafarkzemit** [comment]
> با سلام و وقت بخیر چطور میشه Required رو به input اضافه کرد؟ در واقع در فرم فیلد تاریخ الزامی باشد؟

سلام
من هم این مشکل را دارم. چطور شما مشکل الزامی بودن را حل کردید؟ ممنون میشم راهنمایی بفرمایید.
` <date-picker
            required
            v-model="form.requireDateUtc"
            mode="single"
            :column="1"
            :disable="disableDates"
            auto-submit="false"
            locale="fa"
          >
            <template #before>
              <label for="date"> تاریخ نیاز به دریافت کالا/خدمت* </label>
            </template>
            <template #after>
              <small class="invalid-feedback"> این فیلد الزامی می باشد. </small>
            </template></date-picker
          >`
