### ISSUE TITLE
انتخاب سال و ماه

### ISSUE THREAD

**Issue by shahinesi** [alireza-ab/vue-persian-datepicker#33]
با سلام و خداقوت
من یک سوال داشتم، آیا امکانش هست که در این دیتاپیکر فقط سال و ماه رو داشته باشیم و دیگه روز رو نداشته باشیم؟

**Comment by mrGhamari** [comment]
نه نداره متاسفانه

**Comment by alireza-ab** [comment]
سلام وقت بخیر @shahinesi 
خیر متاسفانه چنین امکانی وجود نداره.
