### ISSUE TITLE
Guide on implementation in Nuxt 3 ? 

### ISSUE THREAD

**Issue by amirsafaricg** [alireza-ab/vue-persian-datepicker#35]
How can this plugin be installed in Nuxt 3 project without giving any errors ? 
the current instruction doesnt work for nuxt 3

**Comment by alireza-ab** [comment]
Hi @amirsafaricg 
Please read this: https://github.com/alireza-ab/vue3-persian-datepicker/issues/8#issuecomment-1859053773
