### ISSUE TITLE
any plans for supporting vue3?

### ISSUE THREAD

**Issue by RyanNorooz** [alireza-ab/vue-persian-datepicker#6]
there aren't any persian datepicker plugins that support vue3 right now
it would be awesome if i could use this plugin in my vue3 project

if you're open for collaboration lemme know, i'd be happy to help

**Comment by alireza-ab** [comment]
Hi @RyanNorooz
If you want to use the vue3 component, see the `next` branch.
I have to write docs for it and publish it.

Working together is great. If you have an idea for development or improvement,  contact me.
