### ISSUE TITLE
کوچک نمایش دادن datePicker 

### ISSUE THREAD

**Issue by devman1917** [alireza-ab/vue-persian-datepicker#8]
سلام من یه مشکلی با کتابخونه دارم اونم اینه که datepicker کوچیک هست.
فونت کل داکیومت سمیم هست. ممنون میشم کمکم کنید 
![image](https://user-images.githubusercontent.com/92359289/147404145-43d8c1c7-3dec-4830-b6a8-b34ff687b330.png)

**Comment by alireza-ab** [comment]
سلام 
از اینجا میتونید مشکلتون رو حل کنید
https://alireza-ab.ir/datepicker/display#column
