### ISSUE TITLE
can not read properties of undefined (reading offsetHeight)

### ISSUE THREAD

**Issue by honarmanly** [alireza-ab/vue-persian-datepicker#9]
I'm using nuxtjs version 2.15.7 and get this error. ssr is set to false. the error shows up when the picker dialog is open and I scroll to see the time picker

**Comment by honarmanly** [comment]
what I should add is that this happens if the height of the picker is more than that of page. a little page scroll could reproduce this error. I test the application on chrome browser.

**Comment by alireza-ab** [comment]
Hi @honarmanly 
Please read this page https://alireza-ab.ir/datepicker/installation#nuxt and do it. And set SSR to true and test it.
